### ISSUE TITLE
Filling Sentinel-5P data gaps

### ISSUE THREAD

**Issue by EmanuelCastanho** [climachine/climfill#1]
Is it possible to apply this algorithm along with some in-situ data to fill gaps in Sentinel-5P data when applying a qa_value > 0.75. If so, do you have any recommendations on how to implement it? I don't see in this algorithm a way to use in-situ measurements as inputs.

**Comment by vbessenbacher** [comment]
Thanks for this comment. The manuscript and the algorithm are currently under review and some changes will be coming, so I recommend to wait until the new release. A way to use in-situ measurements is to put them on a regular grid (albeit with lots of missing values, i.e. everywhere where no in-situ measurement is available). However we have not tested the algorithm with data this sparse.

**Comment by EmanuelCastanho** [comment]
Thank you for replying.
